### ISSUE TITLE
Where can I find the doors?

### ISSUE THREAD

**Issue by MaxImMaxud** [Michal78900/SL-CustomObjects#1]
I downloaded SL CUSTOM OBJECTS
And I want to make a separate zone, but I have everything except doors and elevators.
help please

**Comment by profole** [comment]
Doors aren't in the project due to NW issue. Their textures don't load out of bounce (meaning they would be invisible). Elevators aren't in cause afaik they are actually part of the map itself, making it impossible to add the standard elevators.
You can still animate custom elevators in Unity if you want to though.
Also Michael did say he might add doors back _someday_ (aka never).

**Tl;DR** No doors or elevators in Unity for now.
